title:              Allve ê¸°ìˆ  ë¸”ë¡œê·¸
email:              allvegamedevelop@gmail.com
description:        ì‹œë‹ˆì–´ í”„ë¡œê·¸ë˜ë¨¸ê°€ ë˜ê¸° ìœ„í•œ ì—¬ì •
author:             Allve
profile_name:       ğŸ‘¨â€ğŸ’» ì´ìŠ¹ì¬
profile_introduce:  ğŸŒ± 4ë…„ì°¨ ê²Œì„ ê°œë°œìì…ë‹ˆë‹¤.
profile_bio:        ""
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   
github_username:    AllveGit
facebook_username:  
instagram_username: allve_dev
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
